services:
  - type: web
    name: gympro-backend-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start

  - type: web
    name: gympro-frontend-app
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
